# Generated by Django 4.0.4 on 2022-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer_cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='gamecore.cardmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='gamecore.cardmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
