# Generated by Django 4.0.4 on 2022-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0002_alter_roommodel_options_remove_roommodel_is_ended_and_more'),
        ('authentication', '0002_user_answer_cards_user_cards_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer_cards',
            field=models.ManyToManyField(blank=True, related_name='answers', to='gamecore.cardmodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='cards', to='gamecore.cardmodel'),
        ),
    ]
