version: '3.7'

services:
  web:
    container_name: cards-web
    build: ./backend
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    env_file:
      - ./enviroment/web.env
    ports:
      - 8000:8000

  db:
    image: postgres
    container_name: cards-db
    volumes:
      - ./data/:/var/lib/postgresql
    env_file:
      - ./enviroment/db.env

  ui:
    container_name: cards-ui
    build: ./frontend
    volumes:
      - ./frontend:/app/
    depends_on:
      - web
    env_file:
      - ./enviroment/ui.env
    ports:
      - 3000:3000
