version: '3.7'

services:
  web:
    container_name: cards-web
    build: ./backend
    volumes:
      - ./backend/:/app/
    depends_on:
      - mongo
    command: 'poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    env_file:
      - .env
    ports:
      - '8000:8000'

  mongo:
    image: mongo
    container_name: cards-db
    restart: always
    volumes:
      - ./data/mongodb/:/data/db/
    env_file:
      - .env
    ports:
      - '27017:27017'
