version: '3.7'

services:
  web:
    container_name: cards-web
    build: ./backend
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - $PORT:$PORT

  db:
    image: postgres
    container_name: cards-db
    volumes:
      - ./data/:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
