version: '3.7'

services:
  web:
    container_name: cards-web
    build: ./backend
    volumes:
      - ./backend/:/app/
    command: 'poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    ports:
      - '8000:8000'
