version: '3.7'

services:
  web:
    container_name: cards-web
    build: ./backend
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    env_file:
      - ./enviroment/web.env
      - ./enviroment/db.env
    ports:
      - 8000:8000

  db:
    image: postgres
    container_name: cards-db
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql
    env_file:
      - ./enviroment/db.env

  ui:
    container_name: cards-ui
    build: ./frontend
    volumes:
      - ./frontend:/app/
    depends_on:
      - web
    env_file:
      - ./enviroment/ui.env
    ports:
      - 3000:3000
  
  redis:
    container_name: cards-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    depends_on:
      - web
    volumes: 
      - ./data/redis:/data

  worker:
    container_name: cards-worker
    build:
      context: ./backend
      dockerfile: ./Dockerfile.celery
    command: poetry run celery -A core worker -E
    volumes:
      - ./backend:/app/
    env_file:
      - ./enviroment/web.env
      - ./enviroment/db.env
    depends_on:
      - redis

  flower:
    container_name: flower
    build:
      context: ./backend
      dockerfile: ./Dockerfile.celery
    command: poetry run celery -A core flower
    volumes:
      - ./backend:/app/
    env_file:
      - ./enviroment/web.env
      - ./enviroment/db.env
    depends_on:
      - redis
    ports:
      - 5555:5555
