# Generated by Django 4.0.4 on 2022-05-22 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('question', 'Answer'), ('answer', 'Question')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
