# Generated by Django 4.0.4 on 2022-09-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('answer', 'Answer'), ('question', 'Question')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('round_end_time', models.DateTimeField(auto_now_add=True)),
                ('best_answer_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer_card', to='gamecore.cardmodel')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('question_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_card', to='gamecore.cardmodel')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
