# Generated by Django 4.0.4 on 2022-09-24 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommodel',
            options={'ordering': ('room_state',)},
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='is_ended',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='is_started',
        ),
        migrations.AddField(
            model_name='roommodel',
            name='room_state',
            field=models.IntegerField(choices=[(0, 'Wait for new players'), (1, 'Wait for new round'), (2, 'Wait for users answer'), (3, 'Wait for leader select'), (4, 'Game finished')], default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='best_answer_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer_card', to='gamecore.cardmodel'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='question_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_card', to='gamecore.cardmodel'),
        ),
    ]
