# Generated by Django 4.0.4 on 2022-05-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('round_end_time', models.DateTimeField(auto_now_add=True)),
                ('best_answer_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer_card', to='gamecore.cardmodel')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('question_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_card', to='gamecore.cardmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='gamecore.cardmodel')),
                ('cards', models.ManyToManyField(related_name='cards', to='gamecore.cardmodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.roommodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roommodel',
            name='users',
            field=models.ManyToManyField(related_name='users', through='gamecore.UserRoomModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
