# Generated by Django 4.0.4 on 2022-09-24 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecore', '0002_alter_roommodel_options_remove_roommodel_is_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='best_answer_card',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='answers_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='round_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
