# Generated by Django 4.0.4 on 2022-05-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0002_roommodel_userroommodel_roommodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroommodel',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='gamecore.cardmodel'),
        ),
        migrations.AlterField(
            model_name='userroommodel',
            name='cards',
            field=models.ManyToManyField(null=True, related_name='cards', to='gamecore.cardmodel'),
        ),
    ]
