# Generated by Django 4.0.4 on 2022-09-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0003_alter_userroommodel_answer_alter_userroommodel_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='card_type',
            field=models.CharField(choices=[('answer', 'Answer'), ('question', 'Question')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='userroommodel',
            name='answer',
        ),
        migrations.AddField(
            model_name='userroommodel',
            name='answer',
            field=models.ManyToManyField(related_name='answer', to='gamecore.cardmodel'),
        ),
        migrations.AlterField(
            model_name='userroommodel',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='gamecore.cardmodel'),
        ),
    ]
