"""Create cards model and user room model

Revision ID: 812cfc842f84
Revises: f78691864013
Create Date: 2022-05-19 13:23:03.185933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812cfc842f84'
down_revision = 'f78691864013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardsmodel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('card_type', sa.Enum('question', 'answer', name='cardsenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roommodel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_ended', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('round_end_time', sa.DateTime(), nullable=False),
    sa.Column('leader_id', sa.String(), nullable=True),
    sa.Column('question_card_id', sa.String(), nullable=True),
    sa.Column('funny_card_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['funny_card_id'], ['cardsmodel.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['usermodel.id'], ),
    sa.ForeignKeyConstraint(['question_card_id'], ['cardsmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userroommodel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('answer_card', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['answer_card'], ['cardsmodel.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['roommodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id')
    )
    op.create_table('userroomcardsmodel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_room_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cardsmodel.id'], ),
    sa.ForeignKeyConstraint(['user_room_id'], ['userroommodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_room_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userroomcardsmodel')
    op.drop_table('userroommodel')
    op.drop_table('roommodel')
    op.drop_table('cardsmodel')
    # ### end Alembic commands ###
