"""Create UserToken model for JWT

Revision ID: f78691864013
Revises: 566c1bf537b6
Create Date: 2022-05-17 10:17:41.006133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78691864013'
down_revision = '566c1bf537b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertokenmodel',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('refresh', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertokenmodel')
    # ### end Alembic commands ###
